version: "3.8"

networks:
  main:

services:
  nginx:
    container_name: nginx
    networks:
      - main
    depends_on:
      - main-app

  redis-db:
    container_name: redis-db
    image: redis
    expose:
      - 6379
    networks:
      - main

  main-app:
    container_name: main-app
    restart: always
    environment:
      - REDIS_HOST=redis-db
    expose:
      - 8080
    depends_on:
      - support-1-app
      - support-2-app
      - support-3-app
    networks:
      - main

  support-1-app:
    container_name: support-app-1
    restart: always
    environment:
      - SERVER_NAME=support-1-app
      - REDIS_HOST=redis-db
    depends_on:
      - redis-db
    networks:
      - main

  support-2-app:
    container_name: support-app-2
    restart: always
    environment:
      - SERVER_NAME=support-2-app
      - REDIS_HOST=redis-db
    depends_on:
      - redis-db
    networks:
      - main

  support-3-app:
    container_name: support-app-3
    environment:
      - SERVER_NAME=support-3-app
      - REDIS_HOST=redis-db
    depends_on:
      - redis-db
    networks:
      - main
