version: "3"

networks:
  main:

services:
  nginx:
    networks:
      - main
    depends_on:
      - main-app

  redis-db:
    image: redis
    expose:
      - 6379
    networks:
      - main

  main-app:
    container_name: main-app
    restart: always
    environment:
      - REDIS_HOST=redis-db
    expose:
      - 8080
    depends_on:
      - support-1
      - support-2
      - support-3
    networks:
      - main

  support-1:
    container_name: support-1
    restart: always
    environment:
      - SERVER_NAME=support-1
      - REDIS_HOST=redis-db
    depends_on:
      - redis-db
    networks:
      - main

  support-2:
    container_name: support-2
    restart: always
    environment:
      - SERVER_NAME=support-2
      - REDIS_HOST=redis-db
    depends_on:
      - redis-db
    networks:
      - main

  support-3:
    container_name: support-3
    restart: always
    environment:
      - SERVER_NAME=support-3
      - REDIS_HOST=redis-db
    depends_on:
      - redis-db
    networks:
      - main
