version: "3.8"

services:
  nginx:
    image: ${NGINX_REPO_URL}
    ports:
      - "80:8080"

  main-app:
    image: ${MAIN_APP_REPO_URL}
    command: npm start
    environment:
      - NODE_ENV=production
      - LOGGING_APP_HOST_URL=${LOGGING_APP_HOST_URL}
      - DB_ADMINISTRATION_APP_1_HOST_URL=${DB_ADMINISTRATION_APP_1_HOST_URL}
      - DB_ADMIN_ADMINISTRATION_APP_1_HOST_URL=${DB_ADMIN_ADMINISTRATION_APP_1_HOST_URL}
      - DB_ADMINISTRATION_APP_2_HOST_URL=${DB_ADMINISTRATION_APP_2_HOST_URL}
      - DB_ADMIN_ADMINISTRATION_APP_2_HOST_URL=${DB_ADMIN_ADMINISTRATION_APP_2_HOST_URL}

  support-1-app:
    image: ${SUPPORT_APP_REPO_URL}

  support-2-app:
    image: ${SUPPORT_APP_REPO_URL}

  support-3-app:
    image: ${SUPPORT_APP_REPO_URL}
