version: "3.8"

networks:
  logging-network:
    external: true

  persistence-network:
    external: true

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:8080"

  main-app:
    build:
      context: ./main-app
    volumes:
      - ./main-app/server/:/usr/src/app/server
      - /usr/src/app/server/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - LOGGING_APP_HOST_URL=logging-app:8080
      - DB_ADMINISTRATION_APP_1_HOST_URL=db-administration-app-1:8080
      - DB_ADMIN_ADMINISTRATION_APP_1_HOST_URL=db-admin-administration-app-1:8080
      - DB_ADMINISTRATION_APP_2_HOST_URL=db-administration-app-2:8080
      - DB_ADMIN_ADMINISTRATION_APP_2_HOST_URL=db-admin-administration-app-2:8080
    networks:
      - logging-network
      - persistence-network

  support-1-app:
    build:
      context: ./support-app

  support-2-app:
    build:
      context: ./support-app

  support-3-app:
    build:
      context: ./support-app
