version: "3"

networks:
  log-app-network:
    external: true
  db-access-app-network:
    external: true

services:
  main-app:
    build:
      context: ./main-app
      dockerfile: Dockerfile
    volumes:
      - ./main-app/server/:/usr/src/app/server
      - /usr/src/app/server/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - LOG_APP_URL=log-app:8080
      - DB_ACCESS_APP_1_URL=db-access-app-1:8080
      - DB_ACCESS_ADMIN_APP_1_URL=db-access-app-admin-1:8080
      - DB_ACCESS_APP_2_URL=db-access-app-2:8080
      - DB_ACCESS_ADMIN_APP_2_URL=db-access-app-admin-2:8080
    networks:
      - log-app-network
      - db-access-app-network

  support-1:
    build:
      context: ./support-app

  support-2:
    build:
      context: ./support-app

  support-3:
    build:
      context: ./support-app
