version: "2"

volumes:
  nodemodules_main_app_frontend:
    external: true

services:
  base:
    image: node:alpine
    volumes:
      - nodemodules_main_app_frontend:/app/node_modules
      - .:/app
    working_dir: /app

  install:
    extends:
      service: base
    command: npm i

  build:
    extends:
      service: base
    command: npm run build
